import Footer from '@/components/Footer'
import Header from '@/components/Header'

import QueryProvider from '@/providers/QueryProvider'
import StoreProvider from '@/providers/StoreProvider'
import { QueryClient } from '@tanstack/react-query'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const queryClient = new QueryClient({
	defaultOptions: {
		queries: {
			refetchOnWindowFocus: false
		}
	}
})

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<QueryProvider>
					<StoreProvider>
						<Header />
						<main className="min-h-[90vh] bg-fuchsia-200">{children}</main>
						<Footer />
					</StoreProvider>
				</QueryProvider>
			</body>
		</html>
	)
}
