import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { persistor, store } from '@/store/store'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const queryClient = new QueryClient({
	defaultOptions: {
		queries: {
			refetchOnWindowFocus: false
		}
	}
})

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<QueryClientProvider client={queryClient}>
					<Provider store={store}>
						<PersistGate loading={null} persistor={persistor}>
							<Header />
							<main className="min-h-[90vh] bg-fuchsia-200">{children}</main>
							<Footer />
							<ReactQueryDevtools initialIsOpen={false} />
						</PersistGate>
					</Provider>
				</QueryClientProvider>
			</body>
		</html>
	)
}
