import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { persistor, store } from '@/store/store'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Provider store={store}>
					<PersistGate loading={null} persistor={persistor}>
						<Header />
						<main className="min-h-[90vh] bg-fuchsia-200">{children}</main>
						<Footer />
					</PersistGate>
				</Provider>
			</body>
		</html>
	)
}
