name: Deploy Frontend

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy frontend via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/volosmeister/volosmeister-frontend
          git pull origin master
          cd ~/volosmeister/volosmeister-backend
          docker compose up --build --force-recreate -d frontend
          docker restart nginx
